spring:
  application:
    name: gateway-services
  cloud:
    gateway:
      routes:
        - id: identity-auth-login
          uri: http://identity-service:8080
          predicates:
            - Path=/api/v1/auth/login

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47}

logging:
  level:
    root: INFO
    id.livingatlas.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG