spring:
  application:
    name: gateway-services

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: identity-auth-register
          uri: http://identity-service:8080
          predicates:
            - Path=/api/v1/auth/register
        - id: identity-auth-login
          uri: http://identity-service:8080
          predicates:
            - Path=/api/v1/auth/login
        - id: identity-auth-refresh
          uri: http://identity-service:8080
          predicates:
            - Path=/api/v1/auth/refresh

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:TGluZ29NYWthblNlY3JldEtleUZvckxpdmVuZ0F0bGFzUE9TVEdSU1FMUHJvZHVjdGlvbjIwMjY=}


redpanda:
  bootstrap-servers: ${REDPANDA_BROKERS:redpanda:9092}

logging:
  level:
    root: INFO
    id.livingatlas.gateway: DEBUG
    org.springframework.cloud.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: always